jobs:
# All tasks on Linux
- job: build_all_linux
  displayName: Build all tasks (Linux)
  timeoutInMinutes: 120
  pool:
    vmImage: ubuntu-latest
  variables:
    CI_TEST: true
  steps:
  - task: RunLinter@0
    displayName: RunLinter
  - script: bash check.sh
    displayName: 'Run Linter'
  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    inputs:
      version: 7.0.x
  - script: bash build.sh --target=Test-with-Codecov
    displayName: 'Build and Test'
  - task: PublishTestResults@2
    condition: always()
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
  - task: reportgenerator@5
    displayName: ReportGenerator
    inputs:
      reports: '$(Build.SourcesDirectory)/test/TestResults/*/coverage.cobertura.xml'
      targetdir: '$(Build.SourcesDirectory)/CodeCoverage'
      reporttypes: 'Cobertura'
      assemblyfilters: '-xunit*'
  - script: bash build.sh --target=Upload-Coverage-Azure
    displayName: 'Upload data to Codecov'
